elasticsearchURL: "https://192.168.1.16:9200/"
ApiKey: "SjBDV3hvTUIyMFBuSGhoblktT1U6WlVVUk5WQXhRcWlvV0JQNzF2UHJjUQ=="

accessLogIndex: "workstation-apache-access-logs"
uriIndices: "_cat/indices"
uriClusterHealth: "_cluster/health"
